### ISSUE TITLE
Installation issue at 56%

### ISSUE THREAD

**Issue by nabs13** [webkul/hotelcommerce#58]
Hello, iv tried several times to install qloapps  but it always end at 56%, im running wampserver 2.5, i would really appreciate some guidance please.

![image](https://user-images.githubusercontent.com/23342920/49345720-c4a20780-f680-11e8-86d4-1713b9862ebf.png)

**Comment by sumitwebkul** [comment]
We request you to please create a ticket at https://webkul.uvdesk.com . Please share your FTP details and Url on which you are installing Qloapps.

**Comment by mrtruyen** [comment]
same error. php_error log display:

PHP Fatal error:  Uncaught exception 'PrestaShopException' with message 'Property Connection->ip_address is not valid' in D:\wamp64\www\hotelcommerce\classes\ObjectModel.php:909
Stack trace:
#0 D:\wamp64\www\hotelcommerce\classes\ObjectModel.php(246): ObjectModelCore->validateFields()
#1 D:\wamp64\www\hotelcommerce\classes\Connection.php(77): ObjectModelCore->getFields()
#2 D:\wamp64\www\hotelcommerce\classes\ObjectModel.php(487): ConnectionCore->getFields()
#3 D:\wamp64\www\hotelcommerce\install\classes\xmlLoader.php(447): ObjectModelCore->add(true, false)
#4 D:\wamp64\www\hotelcommerce\install\classes\xmlLoader.php(305): InstallXmlLoader->createEntity('connections', 'connections_1', 'Connection', Array, Array)
#5 D:\wamp64\www\hotelcommerce\install\classes\xmlLoader.php(212): InstallXmlLoader->populateEntity('connections')
#6 D:\wamp64\www\hotelcommerce\install\models\install.php(858): InstallXmlLoader->populateFromXmlFiles()
#7 D:\wamp64\www\hotelcommerce\install\controllers\http\process.php(273): InstallModelInstall->insta in D:\wamp64\www\hotelcommerce\classes\ObjectModel.php on line 909

**Comment by sumitwebkul** [comment]
@mrtruyen  Please follow this issue at QloApps forum https://forums.qloapps.com/topic/48/installation-issues-56/3.
The solution to this issue has already provided.

Thanks.

**Comment by wdammak** [comment]
to close
