### ISSUE TITLE
Error while creating a new hotel in REST

### ISSUE THREAD

**Issue by mohamedsch** [webkul/hotelcommerce#794]
i have this error when i was trying to create a new hotel

```
Fatal error: Uncaught PrestaShopException: Property Category->name is empty in
C:\xampp\htdocs\hotel\classes\ObjectModel.php:965
Stack trace:
#0 C:\xampp\htdocs\hotel\classes\ObjectModel.php(298): ObjectModelCore->validateFieldsLang()
#1 C:\xampp\htdocs\hotel\classes\ObjectModel.php(514): ObjectModelCore->getFieldsLang()
#2 C:\xampp\htdocs\hotel\classes\Category.php(160): ObjectModelCore->add(true, false)
#3 C:\xampp\htdocs\hotel\modules\hotelreservationsystem\classes\HotelBranchInformation.php(642): CategoryCore->add()
#4 C:\xampp\htdocs\hotel\modules\hotelreservationsystem\classes\HotelBranchInformation.php(993):
HotelBranchInformation->addCategory(NULL, '68', Array)
#5 C:\xampp\htdocs\hotel\modules\hotelreservationsystem\classes\HotelBranchInformation.php(920):
HotelBranchInformation->setWsHotelCategories()
#6 C:\xampp\htdocs\hotel\classes\webservice\WebserviceRequest.php(1497): HotelBranchInformation->addWs()
#7 C:\xampp\htdocs\hotel\classes\webservice\WebserviceRequest.php(1306): WebserviceRequestCore->saveEntityFrom in
C:\xampp\htdocs\hotel\classes\ObjectModel.php on line 965
```

it figure out that a country_id and state etc. are needed.

**Comment by shreesh-webkul** [comment]
@mohamedsch 
Thanks for raising this issue, it will surely help us to improve QloApps.
Our team is actively investigating the problem you've reported. We're looking into the details to understand the root cause and identify possible solutions.
